### ISSUE TITLE
Поправить iptables_setup

### ISSUE THREAD

**Issue by RinatFatkhullin** [slovak12345/TestWebSeervice#123]
https://github.com/slovak12345/TestWebSeervice/blob/develop/thirdparty/iptables_setup

Правильный синтаксис

iptables -A DOCKER -t nat -p udp -m udp ! -i br-27a279d42b14 --dport 14550:15650 -j DNAT --to-destination 172.24.0.3:14550-15650

iptables -A DOCKER -p udp -m udp -d 172.24.0.3/16 ! -i br-27a279d42b14 -o br-27a279d42b14 --dport 14550:15650 -j ACCEPT

iptables -A POSTROUTING -t nat -p udp -m udp -s 172.24.0.3/16 -d 172.24.0.3/16 --dport 14550:15650 -j MASQUERADE

Сделать две переменные для значений
br-27a279d42b14
172.24.0.3

**Comment by RinatFatkhullin** [comment]
Поправить передачу параметров в опции --dport
поставить : вместо -
В комментарии привести пример запуска скрипта

**Comment by slovak12345** [comment]
./iptables_setup -network br-27a279d42b14 -ip 172.24.0.3
