### ISSUE TITLE
Разработать структуру приложения шаблона компонента системы характеризующую его многопоточность 

### ISSUE THREAD

**Issue by slovak12345** [slovak12345/TestWebSeervice#13]

**Comment by RinatFatkhullin** [comment]
Параметры для запуска
-с, --config - путь до конфигурационного файла 
-t, --test - проверка конфигурационного файла
-h, --help - вывод помощи по конфигурационным параметрам
-l, --log_file - путь до файла логов
-v, --verbose - изменить уровень логгирования до debug
-d, --daemon - запускать компонент в фоновом режиме
-V, --version - показать номер версии
