### ISSUE TITLE
Добавить mongodb в docker образ

### ISSUE THREAD

**Issue by RinatFatkhullin** [slovak12345/TestWebSeervice#15]

**Comment by RinatFatkhullin** [comment]
После добавления необходимые процессы не запускаются
- mondod
- opensearch
- opensearch-dashboards
- fluent-bit

Дополнительно еще нужна утилита mongo (mongo cli)

**Comment by slovak12345** [comment]
Исправлено в https://github.com/slovak12345/TestWebSeervice/commit/ce76013b2a98d44285dc2367dc0c11d018ca8ba1 для проверки использовать curl http://localhost:27017/
