### ISSUE TITLE
Настроить интеграцию fluent bit, opensearch и opensearch dashboards

### ISSUE THREAD

**Issue by RinatFatkhullin** [slovak12345/TestWebSeervice#2]
Должна работать такая связка:
1. Есть python script, который пишет log с помощью logging в виде json - 1 запись 1 раз в секунду
2. Есть fluent bit, который читает файл с логами и загружает их в opensearch
3. Логи можно просматривать через opensearch dashboards

**Comment by slovak12345** [comment]
Was solved in ba3a523db19f45b10df5dfd9fd8a0ec03a8e6091
