### ISSUE TITLE
Посчитать трудоёмкость разработки luajit и nginx

### ISSUE THREAD

**Issue by RinatFatkhullin** [slovak12345/TestWebSeervice#3]
Количество строк
Примерная трудоёмкость
Примерная стоимость

**Comment by slovak12345** [comment]
scc LuaJIT:
───────────────────────────────────────────────────────────────────────────────
Language                 Files     Lines   Blanks  Comments     Code Complexity
───────────────────────────────────────────────────────────────────────────────
C Header                    81     27504     2500      2400    22604       4998
C                           77     58270     3886      4474    49910      12696
Lua                         29     16064      908      1254    13902       1727
HTML                        13      5854      352         8     5494          0
Batch                        7       842      105         0      737         57
gitignore                    4        24        0         0       24          0
CSS                          2       489        0        24      465          0
Makefile                     2       912       99       202      611         30
C++ Header                   1         9        2         1        6          0
License                      1        56       13         0       43          0
───────────────────────────────────────────────────────────────────────────────
Total                      217    110024     7865      8363    93796      19508
───────────────────────────────────────────────────────────────────────────────
Estimated Cost to Develop (organic) $3,179,719
Estimated Schedule Effort (organic) 21.35 months
Estimated People Required (organic) 13.23
───────────────────────────────────────────────────────────────────────────────
Processed 3303505 bytes, 3.304 megabytes (SI)

**Comment by slovak12345** [comment]
scc nginx:
───────────────────────────────────────────────────────────────────────────────
Language                 Files     Lines   Blanks  Comments     Code Complexity
───────────────────────────────────────────────────────────────────────────────
C                          256    213497    52418      5752   155327      33653
C Header                   134     15898     4804      1077    10017        246
Perl                         4       281       71        38      172         10
Vim Script                   4      1995       90        74     1831          3
SKILL                        3       123       24         0       99          3
Document Type Defin…         2        44       14         0       30          0
HTML                         2        42        2         0       40          0
Shell                        2       234       60        10      164         16
XML                          2     30049     3095        16    26938          0
C++                          1        31        9         3       19          0
Extensible Styleshe…         1       128       39         0       89          0
License                      1        26        0         0       26          0
Makefile                     1        30       10         0       20          0
───────────────────────────────────────────────────────────────────────────────
Total                      413    262378    60636      6970   194772      33931
───────────────────────────────────────────────────────────────────────────────
Estimated Cost to Develop (organic) $6,848,542
Estimated Schedule Effort (organic) 28.57 months
Estimated People Required (organic) 21.29
───────────────────────────────────────────────────────────────────────────────
Processed 7000553 bytes, 7.001 megabytes (SI)
───────────────────────────────────────────────────────────────────────────────
